public with sharing class DreamforceClass {

    //hello
    
    public static String sayHello(){
        return 'Hello dreamforce 22!';
    }

    public static String bye(){
        //please return bye
        return 'bye';
    }

    public static void check(){
        //second change
        //third line
        //4th line
        //5th line
    }

    public static void newMethod(){
        //added from dx repo!
        //i made this change locally
        //i made this change on the sf server
        //change 1
    }

    public static Boolean customerEngineers(){
        return true;
    }
}